project:
  type: website

website:
  title: "Edward Hillenaar Quarto Website"
  navbar:
    right:
      - about.qmd
      - contact.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/HillenaarE95352
      - icon: facebook
        href: https://www.facebook.com/EdwardHillenaar?locale=nl_NL
      - icon: linkedin
        href: https://linkedin.com
format:
  html:
    theme: darkly
    css: styles.scss

editor: visual


