project:
  type: website

website:
  title: "Edward Hillenaar Quarto Website"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/HillenaarE95352
      - icon: facebook
        href: https://www.facebook.com/EdwardHillenaar?locale=nl_NL
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

